<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>soem_driver_ros2</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="edgelord@todo.todo">edgelord</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- <exec_depend>soem_driver</exec_depend> -->
  <exec_depend>soem_driver_slave_interface</exec_depend>
  <!--
    use soem_slave_modules as package name/namespace
    with pluginlib to implicitly create package
  -->
  <exec_depend>soem_slave_modules</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
